# Generated by Django 2.2 on 2019-05-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_data_app', '0002_auto_20190509_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(verbose_name='Описание услуги'),
        ),
    ]
