# Generated by Django 2.2 on 2019-05-09 10:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_data_app', '0003_auto_20190509_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание услуги'),
        ),
    ]
