# Generated by Django 2.2 on 2019-05-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_data_app', '0004_auto_20190509_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(null=True, upload_to='services/images', verbose_name='Картинка'),
        ),
    ]
