# Generated by Django 2.2 on 2019-05-11 18:36

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_data_app', '0005_services_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название отдела')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('icon', models.ImageField(upload_to='department/icons')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='DepartmentSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название слайдера')),
                ('image', models.ImageField(upload_to='departamentslider')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_data_app.Department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'Слайдер Отдела',
                'verbose_name_plural': 'Слайдеры Отделов',
            },
        ),
    ]
