# Generated by Django 2.2 on 2019-05-13 06:44

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_data_app', '0007_auto_20190512_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Под ключ',
                'verbose_name_plural': 'Под ключ',
            },
        ),
        migrations.CreateModel(
            name='KeySlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название слайдера')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/slider', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_data_app.Key', verbose_name='Под ключ')),
            ],
            options={
                'verbose_name': 'Слайдер для под ключ',
                'verbose_name_plural': 'Слайдер под ключ',
                'ordering': ('order',),
            },
        ),
    ]
